name: Deploy docker image

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ensure image name is lowercase
        id: tolowercase
        env:
          IMAGE_NAME_UC: ${{ env.IMAGE_NAME }}
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME_UC,,}" >> ${GITHUB_ENV}

      - name: pull Docker image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ steps.tolowercase.outputs.IMAGE_NAME }}:main

      - name: deploy Docker image
        run: |
          docker stop ${{ steps.tolowercase.outputs.IMAGE_NAME }} || true
          docker rm ${{ steps.tolowercase.outputs.IMAGE_NAME }} || true
          docker run -d --name ${{ steps.tolowercase.outputs.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ steps.tolowercase.outputs.IMAGE_NAME }}:main
